### ISSUE TITLE
czkawka 7.0.0 on chocolatey

### ISSUE THREAD

**Issue by tveyben** [jonasw234/au-packages#13]
Hi jonasw234,
Discussions on chocolatey let me here as it seems you're the maintainer of czkawka on chocolatey (but do not se messages on chocolatey, only on github, hence this post).

I see that czkawka 7.0.0 was release on february 19 thus I am wondering if
* you have been made aware of this (I guess not)
* you're still the maintainer of the package on chocolatey

In other words - how to get choco updated

PS.: I just found the tool, it looks very very promising, and as I try to do all my installs via choco, then... :-)

**Comment by jonasw234** [comment]
Hi @tveyben,
thanks for letting me know!
Should be fixed in https://github.com/jonasw234/au-packages/commit/e1abecd96dc0ae95369bef2141775063791093a2.
Unfortunately, Czkawka changed the naming convention for the releases, so my update script didn’t recognize the new version.

**Comment by tveyben** [comment]
Awesome!
...
but - hmm - I DO see 7.0.0 listed on the choco website but after installing it (choco install czkawka) the logs does not reflect the new version

```
Installing the following packages:
czkawka
By installing, you accept licenses for the packages.
Progress: Downloading czkawka 6.1.0.1... 100%
```
And the GUI validates this (6.1.0 <- likely missing the last ".1" due to the last checksumfix...)


... googling  ...  might be a stale cache somewhere!

trying 
`choco upgrade czkawka --version="'7.0.0'"`

yay - this installs the correct v7
```
You have czkawka v6.1.0.1 installed. Version 7.0.0 is available based on your source(s).
Progress: Downloading czkawka 7.0.0... 100%
```

BUT it will not launch

Choco DO report I have a pending reboot, so I'll try that to see if it helps (but I doubt as I could launch v6....)

Manually downloading the files from the install.ps script
https://github.com/qarmin/czkawka/releases/download/7.0.0/windows_czkawka_gui_gtk_410.zip
and manually executing **czkawka_gui.exe** gives the same result

Thus either my PC is **mad** or v7 is **bad**)
Will reboot and investigate :-)

**Comment by tveyben** [comment]
Hmm - reboot made no difference still does not launch (neither from choco - nor from the manual DL, hence it's a czkawka v7 issue (eg missing depencencies on my machine and silently failing)

This is launchable though
`https://github.com/qarmin/czkawka/releases/download/7.0.0/windows_krokiet.exe`

So perhaps (based on this article from the dev) the problem lies with the **GTK** frontend variant and not the **Slint** frontend variant (which seems to be the maintained path forward...)

**Comment by jonasw234** [comment]
Interesting, thank you for investigating it further! It works fine for me (although I had the same issues with Chocolatey not identifying the updated version, until I manually specified it).
I’ll update the script to update to the Slint frontend variant for the next update.

**Comment by jonasw234** [comment]
After looking a bit more closely at krokiet, it seems to not have all of the features that Czkawka has yet. However, since it’s a single file binary, maybe installing and updating it via https://github.com/marwanhawari/stew might be good enough for you?

**Comment by fabiorzfreitas** [comment]
> After looking a bit more closely at krokiet, it seems to not have all of the features that Czkawka has yet. However, since it’s a single file binary, maybe installing and updating it via [marwanhawari/stew](https://github.com/marwanhawari/stew) might be good enough for you?

Just to add my 2 cents here, if possible I'd really appreciate a Chocolatey package for Krokiet, even if it's still sub-par.

I really wouldn't like to use Stew alongside Chocolatey, it kinda beats the purpose of a centralized management solution.

Thanks :)

**Comment by jonasw234** [comment]
Added in https://github.com/jonasw234/au-packages/commit/3386ba811128942550c019479fc97c132cbc686d, but it usually takes a while until the Chocolatey packages are reviewed: https://community.chocolatey.org/packages/krokiet/7.0.0
It also uses a non-Chocolatey download method and file integrity check, so output in case of download errors might be slightly different from what you’re used to. Chocolatey expects an installer, while this is as I said a single file binary.
